name: Check PR and branch

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: |
          yarn

      - name: Run lint task
        run: |
          yarn lint

      - name: Run build task
        run: |
          yarn build
